import type { CreatureId } from '../ai/creatures';
import type { IconName } from './icons';

/** Dutch speech lines from docs/design/creatures.md (v0.1 is Dutch only). */
export type LineKey =
  | 'idle' | 'thinking' | 'happy' | 'sad' | 'sadResign' | 'celebrating' | 'win' | 'loss' | 'draw' | 'oops'
  | 'worried' | 'surprised' | 'crying' | 'laughing';

export const LINE_ICON: Record<LineKey, IconName> = {
  idle: 'hand', thinking: 'think', happy: 'star', sad: 'rain', sadResign: 'flag', celebrating: 'trophy',
  win: 'handshake', loss: 'handshake', draw: 'handshake', oops: 'rewind',
  worried: 'sweat', surprised: 'burst', crying: 'rain', laughing: 'star',
};

export const LINES: Record<CreatureId, Record<LineKey, string[]>> = {
  wobble: {
    worried: ['Oei, wiebel wiebel! Mijn stukje staat in gevaar!', 'Iek! Waar moet ik nu naartoe stuiteren?'],
    surprised: ['Wauw! Hoe deed je dat nou? Dat zag ik echt niet aankomen!', 'Boing?! Dat was slim, zeg!'],
    crying: ['Boehoe! Mijn mooiste stuk is weg... snif snif.', 'Snif... ik smelt helemaal van verdriet. Boehoehoe!'],
    laughing: ['Hihihi! Die pak ik, boing boing!', 'Hahaha! Wat een geluksstuiter was dat!'],
    idle: ['Jij bent! Boing!', 'Wiebel wiebel, jouw zet! Ik ben benieuwd wat je doet.'],
    thinking: ['Hmm... iene, miene...', 'Welke? Deze dan?'],
    happy: ['Ooh, ik heb er een!', 'Boing! Geluksstuiter!'],
    sad: ['Plets. Jij hebt gewonnen!', 'Ik smelt een beetje.'],
    sadResign: ['Ik geef op! Jij wint!'],
    celebrating: ['Ik won? Hihi!', 'Stuiter stuiter, gewonnen!'],
    win: ['Jij speelt super! Nog eens?'],
    loss: ['Leuk potje! Nog eentje?'],
    draw: ['Gelijk! Boing boing!'],
    oops: ['Boing! Terug maar!'],
  },
  clucky: {
    worried: ['Aaah! Rennen, rennen! Mijn veren staan recht overeind!', 'Tok tok... mijn stuk wordt aangevallen, help!'],
    surprised: ['TOK?! Wauw, wat slim van jou! Dat zag ik niet!', 'Iek! Mijn eierschaal vloog er bijna af van schrik!'],
    crying: ['Boehoe! Mijn mooie stuk is weg... tok... snif.', 'Snif snif, ik verstop me even in mijn ei.'],
    laughing: ['Tok tok tok! Hebbes, en wat voor een!', 'Hahaha! Pik! Die had ik zelf niet verwacht!'],
    idle: ['Jij bent. Voorzichtig hoor!', 'Tok tok... ik wacht. Maar niet te eng doen, hè?'],
    thinking: ['Waar is het veilig?', 'Verstoppen! Nee, wacht... hmm.'],
    happy: ['Pik! Hebbes!', 'Tok! Deed ik dat?'],
    sad: ['Oh jee. Je hebt me!', 'Overal veren. Jij wint!'],
    sadResign: ['Ik geef op! Tok!'],
    celebrating: ['Ik won? Ik WON! Tok!', 'Blije kippendans!'],
    win: ['Jij was zo dapper!'],
    loss: ['Goed gespeeld! Nog eens?'],
    draw: ['Niemand won. Pfoe!'],
    oops: ['Pfoe! Weer terug!'],
  },
  copper: {
    worried: ['Fout! Fout! Mijn stuk staat in gevaar, biep!', 'Biep? Mijn sensoren zeggen: dit is niet goed.'],
    surprised: ['Wauw! Die zet moet ik opslaan in mijn geheugen!', 'Nieuwe zet gezien! Heel slim, dat ga ik onthouden.'],
    crying: ['Biep... boe... mijn lampjes worden er verdrietig van.', 'Olielekje... nee, dat is een traan. Snif, biep.'],
    laughing: ['Biep biep haha! Experiment geslaagd!', 'Hahaha! Mijn antenne gloeit helemaal van plezier!'],
    idle: ['Jij bent. Ik kijk goed!', 'Biep. Jouw zet, vriend. Mijn sensoren staan klaar.'],
    thinking: ['Biep boep... even rekenen...', 'Even goed kijken.'],
    happy: ['Biep! Experiment gelukt!', 'Hebbes! Interessant!'],
    sad: ['Biep... Jij wint. Goed gespeeld.', 'Notitie: meer oefenen.'],
    sadResign: ['Biep... ik geef op.'],
    celebrating: ['Biep biep! Ik won!', 'Mijn lampjes dansen!'],
    win: ['Jij leerde mij iets!'],
    loss: ['Goed potje! Nog een test?'],
    draw: ['Uitslag: gelijk! Interessant!'],
    oops: ['Terugspoelen... biep!'],
  },
  snurk: {
    idle: ['Jij bent... gaap...', 'Zzz... oh! Jouw zet. Ik was even weg.'],
    thinking: ['Hmm... zzz... denken is zo moe.', 'Welke? Ach, deze maar weer.'],
    happy: ['Oh! Ik pakte er een in mijn slaap!', 'Mèèèh! Hebbes!'],
    sad: ['Gaap... jij hebt gewonnen. Knap hoor.', 'Ik ga lekker verder slapen.'],
    sadResign: ['Ik geef op... tijd voor een dutje.'],
    celebrating: ['Ik won? Terwijl ik sliep?!', 'Mèèèh! Slaapfeestje!'],
    win: ['Jij was wakker en ik niet. Knap!'],
    loss: ['Leuk potje! Nog eentje, na mijn dutje?'],
    draw: ['Gelijk! Tijd voor een wolletje slaap.'],
    oops: ['Hè? Droomde ik dat?'],
    worried: ['Mèèèh! Word wakker, mijn stuk!', 'Oei, er staat iets in gevaar... gaap.'],
    surprised: ['Mèh?! Daar schrik ik wakker van!', 'Wauw, die zag ik niet in mijn droom!'],
    crying: ['Boehoe! Mijn wolletje wordt nat van de tranen.', 'Snif... ik wil mijn knuffel.'],
    laughing: ['Hihi, mèèèh! Die pak ik!', 'Hahaha! Slaapwandelend gewonnen!'],
  },
  plons: {
    idle: ['Kwaak! Jij bent!', 'Spring spring, jouw zet!'],
    thinking: ['Waar spring ik heen? Overal!', 'Kwaak... een grote sprong!'],
    happy: ['Plons! Hebbes!', 'Kwaak kwaak! Gevangen met mijn tong!'],
    sad: ['Kwaak... jij wint. Ik spring de vijver in.', 'Plons. Verloren.'],
    sadResign: ['Ik geef op! Kwaak!'],
    celebrating: ['Kwaak! Ik won met springen!', 'Hup, hup, kikkerfeest!'],
    win: ['Jij springt nog beter dan ik!'],
    loss: ['Leuk gesprongen! Nog een keer?'],
    draw: ['Gelijk! Iedereen de vijver in!'],
    oops: ['Terugspringen! Boing!'],
    worried: ['Kwaak?! Mijn stuk moet wegspringen!', 'Oei, waar moet ik heen springen?'],
    surprised: ['Kwaak?! Wat een sprong van jou!', 'Wauw, dat zag ik niet aankomen!'],
    crying: ['Boehoe! Kwaak... ik huil een hele vijver vol.', 'Snif... mijn mooiste springer is weg.'],
    laughing: ['Kwahaha! Die heb ik!', 'Hahaha! Plons, gevangen!'],
  },
  fizz: {
    idle: ['Hup hup! Jij bent!', 'Bruis bruis... ik ben klaar!'],
    thinking: ['Aanvallen? Ja! Aanvallen!', 'De bubbels zeggen... die!'],
    happy: ['Plop! Hebbes!', 'Bruisende graai!'],
    sad: ['Pfff. Mijn bruis is op.', 'Jij wint! Mijn prik is eruit.'],
    sadResign: ['Ik geef op! Alle bubbels zijn weg.'],
    celebrating: ['Bruis plop! Ik won!', 'Bubbelfeest!'],
    win: ['Jij hield me tegen! Cool!'],
    loss: ['Leuk potje! Nog een keer?'],
    draw: ['Gelijk! Bubbel high five!'],
    oops: ['Woesj! Bubbels terug!'],
    worried: ['Oeps, te bruisend! Was dat een val?', 'Help! Mijn bubbels worden zenuwachtig!'],
    surprised: ['Wauw! Mijn bubbels knapten ervan!', 'Wauw! Wat een grote zet!'],
    crying: ['Boehoe! Mijn bubbels worden tranen!', 'Snif... ik ben helemaal plat.'],
    laughing: ['Plop plop haha! Die is van mij!', 'Hahaha! Bruisend gewonnen!'],
  },
  muddle: {
    idle: ['Jij bent! Ooh, een worm!', 'Graaf graaf... oh, jouw zet!'],
    thinking: ['Plan! Wacht, wat was het?', 'Hmm... vergeten. Alweer.'],
    happy: ['Oh! Ik vond er een!', 'Opgegraven!'],
    sad: ['Oh. Verloren? Oeps.', 'Terug mijn hol in.'],
    sadResign: ['Ik geef op. Ik ga graven.'],
    celebrating: ['Ik won? Vergeten te verliezen!', 'Blij graafdansje!'],
    win: ['Jij versloeg me! Knap gedaan!'],
    loss: ['Leuk! Nog eens graven!'],
    draw: ['Niemand won? Nog eens graven!'],
    oops: ['Hè? Dit ken ik!'],
    worried: ['Oei, mijn tunnel stort in!', 'Waar is mijn stuk nou gebleven?'],
    surprised: ['Hè? Waar kwam dat vandaan?', 'Wauw! Jij had een plan!'],
    crying: ['Boehoe! Mijn mooiste stuk is weg... snif.', 'Snif snif, ik kruip diep mijn hol in.'],
    laughing: ['Hihihi! Gevonden in de grond!', 'Hahaha! Wat een schat!'],
  },
  knor: {
    idle: ['Knor! Jij bent.', 'Rinkel rinkel, jouw zet. Heb je iets lekkers?'],
    thinking: ['Wat is het meeste waard? Knor...', 'Hmm... welk stuk past in mijn gleuf?'],
    happy: ['Rinkel! In de spaarpot!', 'Knor knor! Weer wat verdiend!'],
    sad: ['Knor... mijn spaarpot is leeg. Jij wint.', 'Jij bent rijker dan ik. Goed gespeeld!'],
    sadResign: ['Knor... ik geef op.'],
    celebrating: ['Knor! Ik ben de rijkste!', 'Rinkel rinkel, feest!'],
    win: ['Jij hebt mijn spaarpot gekraakt! Knap!'],
    loss: ['Leuk potje! Nog een keer sparen?'],
    draw: ['Gelijk! We delen de munten.'],
    oops: ['Knor! Munten terug in de pot!'],
    worried: ['Knor?! Mijn spaarcenten in gevaar!', 'Oei, iemand wil mijn munten pakken!'],
    surprised: ['Knor?! Dat was een dure zet!', 'Wauw, jij bent slimmer dan ik dacht!'],
    crying: ['Boehoe! Mijn duurste stuk is weg!', 'Snif... mijn spaarpot rammelt niet meer.'],
    laughing: ['Knorhaha! Die is veel waard!', 'Hahaha! Rinkel, in de pot ermee!'],
  },
  stip: {
    idle: ['Jij bent! Ik zit klaar om te vliegen.', 'Zoem! Jouw zet.'],
    thinking: ['Waar kan ik aanvallen?', 'Zoem zoem... schaak geven, dat wil ik!'],
    happy: ['Zoem! Hebbes!', 'Stip stip hoera!'],
    sad: ['Oh... jij wint. Ik vlieg even weg.', 'Mijn stippen worden er verdrietig van.'],
    sadResign: ['Ik geef op! Zoem...'],
    celebrating: ['Zoem zoem! Ik won!', 'Hoera, stippenfeest!'],
    win: ['Jij was sneller dan ik! Knap!'],
    loss: ['Leuk potje! Nog een rondje vliegen?'],
    draw: ['Gelijk! Samen op een bloem zitten.'],
    oops: ['Zoem! Terug naar de bloem!'],
    worried: ['Oei! Mijn koning wordt aangevallen!', 'Zoem?! Dit is gevaarlijk!'],
    surprised: ['Wauw! Die zet had ik niet gezien!', 'Zoem?! Heel slim, zeg!'],
    crying: ['Boehoe! Mijn vleugeltjes hangen omlaag.', 'Snif... ik tel mijn stippen maar.'],
    laughing: ['Zoemhaha! Die pak ik!', 'Hahaha! Wat een aanval!'],
  },
  ijzer: {
    idle: ['Ik bewaak. Jij zet.', 'Jij bent, dappere.'],
    thinking: ['Is mijn koning veilig?', 'Schilden omhoog. Hmm.'],
    happy: ['Klang! Hebbes!', 'Veilig en sterk!'],
    sad: ['Mijn muur viel. Jij wint.', 'Een echte held. Goed zo.'],
    sadResign: ['Ik laat mijn schild zakken.'],
    celebrating: ['De muur houdt! Ik win!', 'Klang klang! Feest!'],
    win: ['Jij brak mijn muur. Wauw!'],
    loss: ['Goed gevochten! Nog eens?'],
    draw: ['Twee muren hielden. Goed zo!'],
    oops: ['Klang! Muur staat weer!'],
    worried: ['Mijn muur heeft een gat!', 'Bescherm de koning!'],
    surprised: ['Jij kwam langs mijn schild!', 'Klang?! Sterke zet!'],
    crying: ['Boehoe... er zit een deuk in mijn schild.', 'Snif... zelfs ijzer kan huilen.'],
    laughing: ['Klanghaha! Die was niet beschermd!', 'Hahaha! Mijn schild wint!'],
  },
  kristal: {
    idle: ['Oehoe. Jij bent.', 'Neem rustig je tijd. Ik wacht.'],
    thinking: ['Oehoe... twee zetten vooruit denken.', 'Eerst kijken, dan pas zetten.'],
    happy: ['Oehoe! Goed gezien van mij.', 'Hebbes! Rustig blijven loont.'],
    sad: ['Oehoe... jij bent slimmer dan een uil!', 'Jij wint. Heel knap gespeeld.'],
    sadResign: ['Ik geef op. Oehoe.'],
    celebrating: ['Oehoe! Ik won!', 'Mijn kristallen glinsteren van blijdschap!'],
    win: ['Jij dacht verder vooruit dan ik!'],
    loss: ['Goed gespeeld! Oefen en probeer het nog eens.'],
    draw: ['Gelijk! Twee slimme uilen.'],
    oops: ['Oehoe! Terug in de tijd.'],
    worried: ['Oehoe?! Daar moet ik over nadenken.', 'Pas op, mijn stuk staat in gevaar.'],
    surprised: ['Oehoe! Die zag zelfs ik niet!', 'Wauw, wat een slimme zet!'],
    crying: ['Boehoe... mijn kristallen worden dof.', 'Snif... dat stuk was mijn liefste.'],
    laughing: ['Oehoehaha! Die liet je staan!', 'Hahaha! Goed opgelet van mij!'],
  },
};
